//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IAccountApi : IBaseApi
{
    [Post("/Account/Add")]
    Task<global::AccountDto> Add(global::AccountDto accountDto);

    [Post("/Account/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::AccountDto> accountDtoList);

    [Delete("/Account/Delete")]
    Task Delete(Guid id);

    [Get("/Account/Get")]
    Task<global::AccountDto> Get(Guid id);

    [Get("/Account/GetAll")]
    Task<List<global::AccountDto>> GetAll();

    [Get("/Account/GetAllFull")]
    Task<List<AccountFull>> GetAllFull();

    [Get("/Account/GetFull")]
    Task<AccountFull> GetFull(Guid id);

    [Get("/Account/GetLast")]
    Task<global::AccountDto> GetLast();

    [Post("/Account/Save")]
    Task<global::AccountDto> Save(global::AccountDto accountDto);
}
