//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IAccountProgrammingFrameworkApi : IBaseApi
{
    [Post("/AccountProgrammingFramework/Add")]
    Task<global::AccountProgrammingFrameworkDto> Add(global::AccountProgrammingFrameworkDto accountProgrammingFrameworkDto);

    [Post("/AccountProgrammingFramework/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::AccountProgrammingFrameworkDto> accountProgrammingFrameworkDtoList);

    [Delete("/AccountProgrammingFramework/Delete")]
    Task Delete(Guid id);

    [Get("/AccountProgrammingFramework/Get")]
    Task<global::AccountProgrammingFrameworkDto> Get(Guid id);

    [Get("/AccountProgrammingFramework/GetAll")]
    Task<List<global::AccountProgrammingFrameworkDto>> GetAll();

    [Get("/AccountProgrammingFramework/GetAllFull")]
    Task<List<AccountProgrammingFrameworkFull>> GetAllFull();

    [Get("/AccountProgrammingFramework/GetFull")]
    Task<AccountProgrammingFrameworkFull> GetFull(Guid id);

    [Get("/AccountProgrammingFramework/GetLast")]
    Task<global::AccountProgrammingFrameworkDto?> GetLast();

    [Post("/AccountProgrammingFramework/Save")]
    Task<global::AccountProgrammingFrameworkDto> Save(global::AccountProgrammingFrameworkDto accountProgrammingFrameworkDto);
}
