//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanySkillsApi : IBaseApi
{
    [Post("/CompanySkills/Add")]
    Task<global::CompanySkillsDto> Add(global::CompanySkillsDto companySkillsDto);

    [Post("/CompanySkills/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanySkillsDto> companySkillsDtoList);

    [Delete("/CompanySkills/Delete")]
    Task Delete(Guid companyId);

    [Get("/CompanySkills/Get")]
    Task<global::CompanySkillsDto> Get(Guid companyId);

    [Get("/CompanySkills/GetAll")]
    Task<List<global::CompanySkillsDto>> GetAll();

    [Get("/CompanySkills/GetAllFull")]
    Task<List<CompanySkillsFull>> GetAllFull();

    [Get("/CompanySkills/GetFull")]
    Task<CompanySkillsFull> GetFull(Guid companyId);

    [Get("/CompanySkills/GetLast")]
    Task<global::CompanySkillsDto> GetLast();

    [Post("/CompanySkills/Save")]
    Task<global::CompanySkillsDto> Save(global::CompanySkillsDto companySkillsDto);
}
