//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyIndustryApi : IBaseApi
{
    [Post("/CompanyIndustry/Add")]
    Task<global::CompanyIndustryDto> Add(global::CompanyIndustryDto companyIndustryDto);

    [Post("/CompanyIndustry/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyIndustryDto> companyIndustryDtoList);

    [Delete("/CompanyIndustry/Delete")]
    Task Delete(Guid companyId);

    [Get("/CompanyIndustry/Get")]
    Task<global::CompanyIndustryDto> Get(Guid companyId);

    [Get("/CompanyIndustry/GetAll")]
    Task<List<global::CompanyIndustryDto>> GetAll();

    [Get("/CompanyIndustry/GetAllFull")]
    Task<List<CompanyIndustryFull>> GetAllFull();

    [Get("/CompanyIndustry/GetFull")]
    Task<CompanyIndustryFull> GetFull(Guid companyId);

    [Get("/CompanyIndustry/GetLast")]
    Task<global::CompanyIndustryDto> GetLast();

    [Post("/CompanyIndustry/Save")]
    Task<global::CompanyIndustryDto> Save(global::CompanyIndustryDto companyIndustryDto);
}
