//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyInfrastructureApi : IBaseApi
{
    [Post("/CompanyInfrastructure/Add")]
    Task<global::CompanyInfrastructureDto> Add(global::CompanyInfrastructureDto companyInfrastructureDtoDto);

    [Post("/CompanyInfrastructure/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyInfrastructureDto> companyInfrastructureDtoDtoList);

    [Delete("/CompanyInfrastructure/Delete")]
    Task Delete(Guid id);

    [Get("/CompanyInfrastructure/Get")]
    Task<global::CompanyInfrastructureDto> Get(Guid id);

    [Get("/CompanyInfrastructure/GetAll")]
    Task<List<global::CompanyInfrastructureDto>> GetAll();

    [Get("/CompanyInfrastructure/GetAllFull")]
    Task<List<CompanyInfrastructureFullFull>> GetAllFull();

    [Get("/CompanyInfrastructure/GetFull")]
    Task<CompanyInfrastructureFullFull> GetFull(Guid id);

    [Get("/CompanyInfrastructure/GetLast")]
    Task<global::CompanyInfrastructureDto> GetLast();

    [Post("/CompanyInfrastructure/Save")]
    Task<global::CompanyInfrastructureDto> Save(global::CompanyInfrastructureDto companyInfrastructureDtoDto);
}
