//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyProgrammingLanguageApi : IBaseApi
{
    [Post("/CompanyProgrammingLanguage/Add")]
    Task<global::CompanyProgrammingLanguageDto> Add(global::CompanyProgrammingLanguageDto companyProgrammingLanguageDto);

    [Post("/CompanyProgrammingLanguage/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyProgrammingLanguageDto> companyProgrammingLanguageDtoList);

    [Delete("/CompanyProgrammingLanguage/Delete")]
    Task Delete(Guid id);

    [Get("/CompanyProgrammingLanguage/Get")]
    Task<global::CompanyProgrammingLanguageDto> Get(Guid id);

    [Get("/CompanyProgrammingLanguage/GetAll")]
    Task<List<global::CompanyProgrammingLanguageDto>> GetAll();

    [Get("/CompanyProgrammingLanguage/GetAllFull")]
    Task<List<CompanyProgrammingLanguageFull>> GetAllFull();

    [Get("/CompanyProgrammingLanguage/GetFull")]
    Task<CompanyProgrammingLanguageFull> GetFull(Guid id);

    [Get("/CompanyProgrammingLanguage/GetLast")]
    Task<global::CompanyProgrammingLanguageDto> GetLast();

    [Post("/CompanyProgrammingLanguage/Save")]
    Task<global::CompanyProgrammingLanguageDto> Save(global::CompanyProgrammingLanguageDto companyProgrammingLanguageDto);
}
