//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyPresentationImageApi : IBaseApi
{
    [Post("/CompanyPresentationImage/Add")]
    Task<global::CompanyPresentationImageDto> Add(global::CompanyPresentationImageDto companyPresentationImageDto);

    [Post("/CompanyPresentationImage/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyPresentationImageDto> companyPresentationImageDtoList);

    [Delete("/CompanyPresentationImage/Delete")]
    Task Delete(Guid companyId);

    [Get("/CompanyPresentationImage/Get")]
    Task<global::CompanyPresentationImageDto> Get(Guid companyId);

    [Get("/CompanyPresentationImage/GetAll")]
    Task<List<global::CompanyPresentationImageDto>> GetAll();

    [Get("/CompanyPresentationImage/GetAllFull")]
    Task<List<CompanyPresentationImageFull>> GetAllFull();

    [Get("/CompanyPresentationImage/GetFull")]
    Task<CompanyPresentationImageFull> GetFull(Guid companyId);

    [Get("/CompanyPresentationImage/GetLast")]
    Task<global::CompanyPresentationImageDto?> GetLast();

    [Post("/CompanyPresentationImage/Save")]
    Task<global::CompanyPresentationImageDto> Save(global::CompanyPresentationImageDto companyPresentationImageDto);
}
