//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyLogoApi : IBaseApi
{
    [Post("/CompanyLogo/Add")]
    Task<global::CompanyLogoDto> Add(global::CompanyLogoDto companyLogoDto);

    [Post("/CompanyLogo/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyLogoDto> companyLogoDtoList);

    [Delete("/CompanyLogo/Delete")]
    Task Delete(Guid companyId);

    [Get("/CompanyLogo/Get")]
    Task<global::CompanyLogoDto> Get(Guid companyId);

    [Get("/CompanyLogo/GetAll")]
    Task<List<global::CompanyLogoDto>> GetAll();

    [Get("/CompanyLogo/GetAllFull")]
    Task<List<CompanyLogoFull>> GetAllFull();

    [Get("/CompanyLogo/GetFull")]
    Task<CompanyLogoFull> GetFull(Guid companyId);

    [Get("/CompanyLogo/GetLast")]
    Task<global::CompanyLogoDto?> GetLast();

    [Post("/CompanyLogo/Save")]
    Task<global::CompanyLogoDto> Save(global::CompanyLogoDto companyLogoDto);
}
