//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyApi : IBaseApi
{
    [Post("/Company/Add")]
    Task<global::CompanyDto> Add(global::CompanyDto companyDto);

    [Post("/Company/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyDto> companyDtoList);

    [Delete("/Company/Delete")]
    Task Delete(Guid id);

    [Get("/Company/Get")]
    Task<global::CompanyDto> Get(Guid id);

    [Get("/Company/GetAll")]
    Task<List<global::CompanyDto>> GetAll();

    [Get("/Company/GetAllFull")]
    Task<List<CompanyFull>> GetAllFull();

    [Get("/Company/GetFull")]
    Task<CompanyFull> GetFull(Guid id);

    [Get("/Company/GetLast")]
    Task<global::CompanyDto?> GetLast();

    [Post("/Company/Save")]
    Task<global::CompanyDto> Save(global::CompanyDto companyDto);
}
