//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface ICompanyBenefitApi : IBaseApi
{
    [Post("/CompanyBenefit/Add")]
    Task<global::CompanyBenefitDto> Add(global::CompanyBenefitDto companyBenefitDto);

    [Post("/CompanyBenefit/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::CompanyBenefitDto> companyBenefitDtoList);

    [Delete("/CompanyBenefit/Delete")]
    Task Delete(Guid id);

    [Get("/CompanyBenefit/Get")]
    Task<global::CompanyBenefitDto> Get(Guid id);

    [Get("/CompanyBenefit/GetAll")]
    Task<List<global::CompanyBenefitDto>> GetAll();

    [Get("/CompanyBenefit/GetAllFull")]
    Task<List<CompanyBenefitFull>> GetAllFull();

    [Get("/CompanyBenefit/GetFull")]
    Task<CompanyBenefitFull> GetFull(Guid id);

    [Get("/CompanyBenefit/GetLast")]
    Task<global::CompanyBenefitDto?> GetLast();

    [Post("/CompanyBenefit/Save")]
    Task<global::CompanyBenefitDto> Save(global::CompanyBenefitDto companyBenefitDto);
}
