//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IDistrictImageApi : IBaseApi
{
    [Post("/DistrictImage/Add")]
    Task<global::DistrictImageDto> Add(global::DistrictImageDto districtImageDto);

    [Post("/DistrictImage/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::DistrictImageDto> districtImageDtoList);

    [Delete("/DistrictImage/Delete")]
    Task Delete(Guid districtId);

    [Get("/DistrictImage/Get")]
    Task<global::DistrictImageDto> Get(Guid districtId);

    [Get("/DistrictImage/GetAll")]
    Task<List<global::DistrictImageDto>> GetAll();

    [Get("/DistrictImage/GetAllFull")]
    Task<List<DistrictImageFull>> GetAllFull();

    [Get("/DistrictImage/GetFull")]
    Task<DistrictImageFull> GetFull(Guid districtId);

    [Get("/DistrictImage/GetLast")]
    Task<global::DistrictImageDto?> GetLast();

    [Post("/DistrictImage/Save")]
    Task<global::DistrictImageDto> Save(global::DistrictImageDto districtImageDto);
}
