//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IDistrictApi : IBaseApi
{
    [Post("/District/Add")]
    Task<global::DistrictDto> Add(global::DistrictDto districtDto);

    [Post("/District/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::DistrictDto> districtDtoList);

    [Delete("/District/Delete")]
    Task Delete(Guid id);

    [Get("/District/Get")]
    Task<global::DistrictDto> Get(Guid id);

    [Get("/District/GetAll")]
    Task<List<global::DistrictDto>> GetAll();

    [Get("/District/GetAllFull")]
    Task<List<DistrictFull>> GetAllFull();

    [Get("/District/GetFull")]
    Task<DistrictFull> GetFull(Guid id);

    [Get("/District/GetLast")]
    Task<global::DistrictDto> GetLast();

    [Post("/District/Save")]
    Task<global::DistrictDto> Save(global::DistrictDto districtDto);
}
