//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IIndustryApi : IBaseApi
{
    [Post("/Industry/Add")]
    Task<global::IndustryDto> Add(global::IndustryDto industryDto);

    [Post("/Industry/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::IndustryDto> industryDtoList);

    [Delete("/Industry/Delete")]
    Task Delete(Guid id);

    [Get("/Industry/Get")]
    Task<global::IndustryDto> Get(Guid id);

    [Get("/Industry/GetAll")]
    Task<List<global::IndustryDto>> GetAll();

    [Get("/Industry/GetAllFull")]
    Task<List<IndustryFull>> GetAllFull();

    [Get("/Industry/GetFull")]
    Task<IndustryFull> GetFull(Guid id);

    [Get("/Industry/GetLast")]
    Task<global::IndustryDto?> GetLast();

    [Post("/Industry/Save")]
    Task<global::IndustryDto> Save(global::IndustryDto industryDto);
}
