//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IInfrastructureApi : IBaseApi
{
    [Post("/Infrastructure/Add")]
    Task<global::InfrastructureDto> Add(global::InfrastructureDto infrastructureDto);

    [Post("/Infrastructure/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::InfrastructureDto> infrastructureDtoList);

    [Delete("/Infrastructure/Delete")]
    Task Delete(Guid companyId);

    [Get("/Infrastructure/Get")]
    Task<global::InfrastructureDto> Get(Guid companyId);

    [Get("/Infrastructure/GetAll")]
    Task<List<global::InfrastructureDto>> GetAll();

    [Get("/Infrastructure/GetAllFull")]
    Task<List<InfrastructureFull>> GetAllFull();

    [Get("/Infrastructure/GetFull")]
    Task<InfrastructureFull> GetFull(Guid companyId);

    [Get("/Infrastructure/GetLast")]
    Task<global::InfrastructureDto> GetLast();

    [Post("/Infrastructure/Save")]
    Task<global::InfrastructureDto> Save(global::InfrastructureDto infrastructureDto);
}
