//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.ApiClient.Apis.Base;
using Refit;

namespace ooeentwickleruno.apiclient;

public partial interface IIssueTrackerApi : IBaseApi
{
    [Post("/IssueTracker/Add")]
    Task<global::IssueTrackerDto> Add(global::IssueTrackerDto issueTrackerDto);

    [Post("/IssueTracker/AddRange")]
    Task AddRange(System.Collections.Generic.List<global::IssueTrackerDto> issueTrackerDtoList);

    [Delete("/IssueTracker/Delete")]
    Task Delete(Guid id);

    [Get("/IssueTracker/Get")]
    Task<global::IssueTrackerDto> Get(Guid id);

    [Get("/IssueTracker/GetAll")]
    Task<List<global::IssueTrackerDto>> GetAll();

    [Get("/IssueTracker/GetAllFull")]
    Task<List<IssueTrackerFull>> GetAllFull();

    [Get("/IssueTracker/GetFull")]
    Task<IssueTrackerFull> GetFull(Guid id);

    [Get("/IssueTracker/GetLast")]
    Task<global::IssueTrackerDto> GetLast();

    [Post("/IssueTracker/Save")]
    Task<global::IssueTrackerDto> Save(global::IssueTrackerDto issueTrackerDto);
}
