name: Build and deploy .NET Core application to Web App ooeentwickler
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - master
  push:
    branches:
    - master
  workflow_dispatch: # This line adds the manual trigger option 

env:
  AZURE_STATIC_WEBAPP_NAME: ooeentwickler
  APP_DIRECTORY: ./src/ooeentwickleruno/ooeentwickleruno.Wasm/Release/net8.0/dist
  API_DIRECTORY: ''
  OUTPUT: ./src/ooeentwickleruno/ooeentwickleruno.Wasm/wwwroot
  DEPLOYMENT_ENVIRONMENT: preview

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Ensure this matches the version you need
    - run: |
        cd ./src/ooeentwickleruno/ooeentwickleruno.Wasm
        dotnet build -c Release
    continue-on-error: true

    - name: Show content of CompanyRepository.g.cs
      if: always()
      run: cat ./src/ooeentwickleruno/ApiConnector/ooeentwickleruno.apiclient/Api.Generator/Api.Generator.Generators.WebApiGenerator/Repositories/CompanyRepository.g.cs

    - id: builddeploy
      name: Build And Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.ooeentwickler_SPN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        deployment_environment: ${{env.DEPLOYMENT_ENVIRONMENT}}
        app_location: ${{ env.APP_DIRECTORY }}
        output_location: ${{ env.OUTPUT }}
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request Job
    runs-on: ubuntu-latest
    steps:
    - id: closepullrequest
      name: Close Pull Request
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.ooeentwickler_SPN }}
        action: close
        repo_token: ${{ secrets.GITHUB_TOKEN }}
